logging:
  level:
    pl:
      szymczak: debug
dts:
  file:
    path: 'C:/Data/'
    name: 'generated.json'
spring:
#  datasource:
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
#    url: jdbc:hsqldb:hsql://localhost/testdb
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        generate_statistics: true
        order_inserts: true
